fix 04_testcode
katsunoritakahashi/rspec_app_exam pull request #1
Opened 2021-02-12 03:03 UTC by katsunoritakahashi

課題完了いたしました。
FIXME: テストが失敗するので、成功するように修正。
TODO: 記載事項に沿ってリファクタリング。

ご確認願います。

2021-02-12 06:24 UTC, yuji91 requested changes
修正はほぼOKです。
2点、修正依頼と細かい指摘事項を記載しました。
それぞれ対応するコミットの単位を分けて修正をお願いしますm(_ _)m

2021-02-12 06:24 UTC, yuji91 commented on spec/system/task_spec.rb
> +        visit project_tasks_path(project)
ここで`visit`すると`click_link 'View Todos'`の遷移先が間違っていた場合、それに気づくことなくテストが成功してしまいます。
`byebug`で`page.body`で確認できる内容を変える方針で修正方法を考えてみてください。

2021-02-12 06:24 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id) }
Factoryに`association`を設定すると`project_id`の指定は省略できます！

コード量を減らして見通しが良くなるので試してみてください。
```suggestion
  let(:task) { create(:task) }
```

2021-02-12 07:23 UTC, katsunoritakahashi commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id) }
fc7f9ca でアソシエーションを設定しました。

2021-02-12 07:50 UTC, katsunoritakahashi commented on spec/system/task_spec.rb
> +        visit project_tasks_path(project)
a945230 でbyebugをreqireしました。
「page.bodyで確認できる内容を変える方針」というのがあまり理解できておらず、どうすることになるのでしょうか？

2021-02-12 08:53 UTC, yuji91 commented on spec/system/task_spec.rb
> +        visit project_tasks_path(project)
`require`する必要はないですね。
`click_link 'View Todos'`の後に`byebug`を記載して、デバッグした際の`page.body`の返り値を確認してください。

その事象から何が考察できるかが分かると良いです。

2021-02-12 08:54 UTC, yuji91 requested changes
修正時のコミットには`Fix: 修正内容`と言う形でコミットメッセージにPrefixをつけると見やすいかと思います！
https://www.tam-tam.co.jp/tipsnote/program/post16686.html

2021-02-12 12:11 UTC, katsunoritakahashi commented on spec/system/task_spec.rb
> +        visit project_tasks_path(project)
c58dc32 で修正加えました。
visitで画面遷移させるのではなく、あくまでボタンリンク先の画面をテストする形にいたしました。

2021-02-13 08:33 UTC, katsunoritakahashi commented on spec/system/task_spec.rb
> +        visit project_tasks_path(project)
860b788 でテスト実行時にブラウザを表示させるよう修正いたしました。

2021-02-13 09:34 UTC, katsunoritakahashi commented on spec/system/task_spec.rb
> +        visit project_tasks_path(project)
21ae73e　取り消しました

2021-02-14 09:20 UTC, katsunoritakahashi commented on spec/system/task_spec.rb
> +        visit project_tasks_path(project)
2689e31 で、確認内容を新規ウインドウに切り替えいたしました。
byebug＋page.bodyの実行結果が新規ウインドウ（タスク一覧画面）となっていること確認済みです。
ご確認よろしくおねがいします。

2021-02-15 02:33 UTC, yuji91 requested changes
最後細かい点だけ指摘しました。

現場ではレビュー依頼前にケアレスミスがないか、一度ファイル差分を全体チェックするのも良いかと思います！
https://github.com/katsunoritakahashi/rspec_app_exam/pull/1/files

2021-02-15 02:33 UTC, yuji91 commented on spec/system/task_spec.rb
> +        binding.irb
デバッグ用のメソッドが残っちゃってますね

2021-02-15 02:45 UTC, katsunoritakahashi commented on spec/system/task_spec.rb
> +        binding.irb
c60e5a5 にて「binding.irb」削除いたしました。
注意不足でした申し訳ありません。今後は依頼する前にコード差分をしっかり確認した上でご依頼するよう気をつけます。

2021-02-15 03:03 UTC, yuji91 approved these changes
LGTMです！

2021-02-15 03:39 UTC, merged